spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?createDatabaseIfNotExist=true&serverTimezone=Europe/Kiev&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: ${MYSQL_PASSWORD}
    sqlScriptEncoding: utf8

  jpa.hibernate.ddl-auto: none

  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#Annealing simulation properties
temperature: 10000
numberOfIterations: 100000
coolingRate: 0.99